/*
 * API Articulos
 * Prueba para desafío de implementación
 *
 * OpenAPI spec version: 1.0.0
 * Contact: random@deltaquo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cl.ingerencia.client.algolia.swagger.codegen.model;

import java.util.Objects;
import cl.ingerencia.client.algolia.swagger.codegen.model.Hit;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Articulos
 */

public class Articulos {
  @JsonProperty("hits")
  private List<Hit> hits = null;

  @JsonProperty("exhaustiveNbHits")
  private Boolean exhaustiveNbHits = null;

  @JsonProperty("hitsPerPage")
  private Integer hitsPerPage = null;

  @JsonProperty("nbHits")
  private Integer nbHits = null;

  @JsonProperty("nbPages")
  private Integer nbPages = null;

  @JsonProperty("page")
  private Integer page = null;

  @JsonProperty("params")
  private String params = null;

  @JsonProperty("processingTimeMS")
  private Integer processingTimeMS = null;

  @JsonProperty("query")
  private String query = null;

  public Articulos hits(List<Hit> hits) {
    this.hits = hits;
    return this;
  }

  public Articulos addHitsItem(Hit hitsItem) {
    if (this.hits == null) {
      this.hits = new ArrayList<>();
    }
    this.hits.add(hitsItem);
    return this;
  }

   /**
   * Get hits
   * @return hits
  **/
  @ApiModelProperty(value = "")
  public List<Hit> getHits() {
    return hits;
  }

  public void setHits(List<Hit> hits) {
    this.hits = hits;
  }

  public Articulos exhaustiveNbHits(Boolean exhaustiveNbHits) {
    this.exhaustiveNbHits = exhaustiveNbHits;
    return this;
  }

   /**
   * Get exhaustiveNbHits
   * @return exhaustiveNbHits
  **/
  @ApiModelProperty(value = "")
  public Boolean isExhaustiveNbHits() {
    return exhaustiveNbHits;
  }

  public void setExhaustiveNbHits(Boolean exhaustiveNbHits) {
    this.exhaustiveNbHits = exhaustiveNbHits;
  }

  public Articulos hitsPerPage(Integer hitsPerPage) {
    this.hitsPerPage = hitsPerPage;
    return this;
  }

   /**
   * Get hitsPerPage
   * @return hitsPerPage
  **/
  @ApiModelProperty(value = "")
  public Integer getHitsPerPage() {
    return hitsPerPage;
  }

  public void setHitsPerPage(Integer hitsPerPage) {
    this.hitsPerPage = hitsPerPage;
  }

  public Articulos nbHits(Integer nbHits) {
    this.nbHits = nbHits;
    return this;
  }

   /**
   * Get nbHits
   * @return nbHits
  **/
  @ApiModelProperty(value = "")
  public Integer getNbHits() {
    return nbHits;
  }

  public void setNbHits(Integer nbHits) {
    this.nbHits = nbHits;
  }

  public Articulos nbPages(Integer nbPages) {
    this.nbPages = nbPages;
    return this;
  }

   /**
   * Get nbPages
   * @return nbPages
  **/
  @ApiModelProperty(value = "")
  public Integer getNbPages() {
    return nbPages;
  }

  public void setNbPages(Integer nbPages) {
    this.nbPages = nbPages;
  }

  public Articulos page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @ApiModelProperty(value = "")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public Articulos params(String params) {
    this.params = params;
    return this;
  }

   /**
   * Get params
   * @return params
  **/
  @ApiModelProperty(value = "")
  public String getParams() {
    return params;
  }

  public void setParams(String params) {
    this.params = params;
  }

  public Articulos processingTimeMS(Integer processingTimeMS) {
    this.processingTimeMS = processingTimeMS;
    return this;
  }

   /**
   * Get processingTimeMS
   * @return processingTimeMS
  **/
  @ApiModelProperty(value = "")
  public Integer getProcessingTimeMS() {
    return processingTimeMS;
  }

  public void setProcessingTimeMS(Integer processingTimeMS) {
    this.processingTimeMS = processingTimeMS;
  }

  public Articulos query(String query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(value = "")
  public String getQuery() {
    return query;
  }

  public void setQuery(String query) {
    this.query = query;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Articulos articulos = (Articulos) o;
    return Objects.equals(this.hits, articulos.hits) &&
        Objects.equals(this.exhaustiveNbHits, articulos.exhaustiveNbHits) &&
        Objects.equals(this.hitsPerPage, articulos.hitsPerPage) &&
        Objects.equals(this.nbHits, articulos.nbHits) &&
        Objects.equals(this.nbPages, articulos.nbPages) &&
        Objects.equals(this.page, articulos.page) &&
        Objects.equals(this.params, articulos.params) &&
        Objects.equals(this.processingTimeMS, articulos.processingTimeMS) &&
        Objects.equals(this.query, articulos.query);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hits, exhaustiveNbHits, hitsPerPage, nbHits, nbPages, page, params, processingTimeMS, query);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Articulos {\n");
    
    sb.append("    hits: ").append(toIndentedString(hits)).append("\n");
    sb.append("    exhaustiveNbHits: ").append(toIndentedString(exhaustiveNbHits)).append("\n");
    sb.append("    hitsPerPage: ").append(toIndentedString(hitsPerPage)).append("\n");
    sb.append("    nbHits: ").append(toIndentedString(nbHits)).append("\n");
    sb.append("    nbPages: ").append(toIndentedString(nbPages)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    processingTimeMS: ").append(toIndentedString(processingTimeMS)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

